### ISSUE TITLE
How to prevent opening/closing of tree nodes on right-click

### ISSUE THREAD

**Issue by granicz** [dojo/dijit#178] opened 2020-04-30 15:20 UTC
On this demo:

https://dojotoolkit.org/reference-guide/1.10/dijit/Tree.html#context-menu

When you right-click a parent item, it opens/closes instead of staying as is before opening the context menu. How do you stop propagating that event?

**Comment by msssk** [comment] 2020-05-04 20:55
This was fixed in Dojo [1.10.5](https://github.com/dojo/dojo/commit/40012adf7d42cfff8feb34363b48ec83592a441b), the demo is running 1.10.0.

**Closed by msssk** 2020-05-04 20:55 UTC

**Comment by granicz** [comment] 2020-05-05 00:23
Any idea why 1.10.5 doesn't run with https://github.com/dojo/js-doc-parse ? Sorry for the noob question, we are relying on this tool to generate an F#+WebSharper binding. Any help would be much appreciated.

**Comment by msssk** [comment] 2020-05-05 06:42
I'm not sure and unfortunately that project is no longer maintained. Efforts to create typing information for the Dojo toolkit have transitioned to TypeScript and [dojo/typings](https://github.com/dojo/typings).

**Comment by granicz** [comment] 2020-05-05 10:39
I see dojo/typings has recent commits but has only dojo 1.11 - isn't dojo1 at 1.16 now?

**Comment by dylans** [comment] 2020-05-08 00:50
@granicz 
So the issue is basically that the dojo/typings actually probably work better against 1.16 than 1.11 but are designed to hopefully work with 1.11 and newer. We are planning an updated release soon (next week).
